apiVersion: "navigator.jetstack.io/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: "demo"
spec:
  version: "3.11.1"
  cqlPort: 9042
  sysctls:
  - "vm.max_map_count=0"
  nodePools:
  - name: "RingNodes"
    replicas: 3
    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "default"
